### ISSUE TITLE
update jenkins to (2.289.1)

### ISSUE THREAD

**Issue by lindeengineering** [SAP/devops-docker-cx-server#105]
Hi team,

are there any plans to update jenkins to the latest version? Unfortunately we are not able to update some plugins as they require a higher minium version of jenkins

**Comment by fwilhe** [comment]
Hi,

Thanks for the notice. Our automated image builds got suspended by github. I re enabled them and released v64 (image `ppiper/jenkins-master:v64`) which now has the requested Jenkins version. The "latest" tag is not yet updated, but will be on Monday.

Kind regards

Florian
