### ISSUE TITLE
Backup of server fails randomly

### ISSUE THREAD

**Issue by LaKoBlue** [SAP/devops-docker-cx-server#41]
The command cx-server backup fails randomly with an error stating that the volume name shouldn't be empty.

This message is sourced in the way the container id is determined. Script cx-server-companion.sh uses this command to determine it (line 12) 
 `$(head -n 1 /proc/self/cgroup | rev | cut -d '/' -f1 | rev)`

Unfortunately the order of/proc/self/cgroup entries is not guaranteed. Occasionally the entry 6 for rdma is the first resulting in an empty container id.

Better approach might be the following statement to always determine the container id by using the memory entry using grep:
`grep memory /proc/self/cgroup | rev | cut -d '/' -f1 | rev`

**Comment by fwilhe** [comment]
Hi @LaKoBlue 

thanks for reporting the issue. It looks like you did already investigate so deeply that you could create a PR with little effort. If you would like to do that, please do it.

Kind regards

Florian

**Comment by LaKoBlue** [comment]
As you and your colleagues from SAP SE heavily insist on, I did.

See https://github.com/SAP/devops-docker-cx-server/pull/42

**Comment by fwilhe** [comment]
> As you and your colleagues from SAP SE heavily insist on, I did.
> 
> See #42

Thank you, will review tomorrow
