### ISSUE TITLE
role-based auth strategy

### ISSUE THREAD

**Issue by T1mey** [SAP/devops-docker-cx-server#65]
Is it possible to include the role-based auth. strategy plugin as default plugin in this image?

**Comment by fwilhe** [comment]
Hi @T1mey 

we try to keep the number of plugins we include in the default image low as this has effects on the image size and startup time of Jenkins. I'm not against including the plugin, but I would like to understand which benefit it provides. Would you mind elaborating what usage scenario this plugin permits which is currently not possible?

**Comment by T1mey** [comment]
I would like to restrict the access of persons to the build projects they belong to. 
As base of this we would like to use LDAP groups.

Example:
If a user has the ldap group for app A and B he should only see those 2 projects in Jenkins. Means he will not see C and D.

**Comment by fwilhe** [comment]
Hi @T1mey, the latest release from today includes the plugin.
