### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by T1mey** [SAP/devops-docker-cx-server#69]
Could it be that under v10 is a really old Jenkins published?

2.204.5

is starting...

**Comment by fwilhe** [comment]
Thanks for the hint, there was a hickup in the release process, I guess something went wrong there. I've triggered a new release just now which will be `v11` then. The images should be available within about an hour if that works well.

**Comment by fwilhe** [comment]
Ok, `v11` has Jenkins `Jenkins v2.222.3`.

Please don't use `v10`.

Thanks again for the hint, I've not noticed this issue so far 👍
