### ISSUE TITLE
Error on starting cx-server

### ISSUE THREAD

**Issue by miyasuta** [SAP/devops-docker-cx-server#70]
Hello.

When I executed `./cx-server start` I got below error.

`failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/98fb0a19c4e5511d64c34284b0f6edb3ac78a7de359636ab51122761011a4c3c/merged: too many levels of symbolic links
[Error] Failed to pull sonatype/nexus3:3.21.1.`

I'm trying to run cx-server on Ubuntu 20.04.

The whole log is blow:

latest: Pulling from ppiper/cx-server-companion
Digest: sha256:e0baf428a0ed47094709194dfa736ac7e7bdfd016ad553f74bae7f97408b029e
Status: Image is up to date for ppiper/cx-server-companion:latest
Checking for new version of Cx Server Docker image... 'ppiper/jenkins-master:latest' is up to date.
\>> docker network connect cx-network 37874310a429046eaf5c0a48f66aa35106799923d5f3027c941a7537c1da5c09
\>> docker pull sonatype/nexus3:3.21.1
3.21.1: Pulling from sonatype/nexus3
eae5d284042d: Already exists 
ff6f434a470a: Already exists 
e9af863226f9: Already exists 
9a5bca2ddc42: Extracting  216.2MB/216.2MB
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/98fb0a19c4e5511d64c34284b0f6edb3ac78a7de359636ab51122761011a4c3c/merged: too many levels of symbolic links
[Error] Failed to pull sonatype/nexus3:3.21.1.

**Comment by miyasuta** [comment]
Hi, I pulled sonatype/nexus3:3.21.1. directly from Docker hub and after that ran `./cx-server start`.
This resolved the issue.

**Comment by fwilhe** [comment]
Thanks for reporting, I have not seen that issue before. Good that you found a workaround. Despite that I would be interested to understand how that happened. So you said you're using ubuntu 20.04, maybe that is some version incompatibility that we're not yet aware of.

Can you share the output of `docker info` and `docker version` on your server? From what source did you install docker? The official ubuntu repo? Via Docker's homepage?

**Comment by miyasuta** [comment]
Hi Florian,

I installed docker by following below instructions.
https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

As stable repository for Ubuntu 20.04 has not yet been released, I used below command to set up repository. (this was suggested in https://askubuntu.com/questions/1230189/how-to-install-docker-community-on-ubuntu-20-04-lts).
`$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   bionic \
   stable"`

**docker info**
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-28-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 4.576GiB
 Name: mio-VirtualBox
 ID: RNML:IA6Y:66MH:F2YW:6HSA:MZTU:I7HJ:MLYD:GVOT:UBD7:5S27:H5P2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


**docker version**
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
