### ISSUE TITLE
Security with role based strategy

### ISSUE THREAD

**Issue by T1mey** [SAP/devops-docker-cx-server#72]
Hello,

as we configured the security with "role based strategy" we get a warning in Jenkins saying

![image](https://user-images.githubusercontent.com/10464878/81403291-598d1800-9133-11ea-925e-6f4f56487a69.png)

As our requirement is, that a user should only see and access builds that he is authorized to.
As the warning is saying that this can only be garanteed if 

> It is recommended that you install Authorize Project Plugin or another plugin implementing the QueueItemAuthenticator extension point.

we would like to request this to be installed as "standard" cx-server plugin.

**Comment by fwilhe** [comment]
Hi @T1mey 

Resolved with #73, will be part of the release on Monday.

Have a nice weekend.
