### ISSUE TITLE
Timeout of 120 secs waiting for nexus is too short on some servers

### ISSUE THREAD

**Issue by matteoprinetti** [SAP/devops-docker-cx-server#81]
Can you please change the timeout of cx-server-companion.sh to 180 ? 

 function wait_for_nexus_started()
 493 {
 494     echo -n "Waiting for the nexus server to start"
 495     wait_for_successful_start 120 "${nexus_container_name}" curl --noproxy localhost --silent -X GET http://localhost:8081/     service/rest/v1/script --header 'Authorization: Basic YWRtaW46YWRtaW4xMjM=' --header 'Content-Type: application/json'
 496 }

my server needs 140 secs to start and it fails there. I cannot change it myself as Im using the piper bootstrap. 

Thanks
Matteo Prinetti

**Comment by fwilhe** [comment]
Hi Matteo,

timeouts are always a bit arbitrary, but I think 3 minutes is ok. PR is open, when it is merged the new image with tag `latest` will be built, and it will be included in our next weekly release.

Hope this helps.

Kind regards

Florian

**Comment by fwilhe** [comment]
Hi @matteoprinetti, is merged and images are rebuilt on the `latest` tag, I hope this resolves the issue for you.

**Comment by matteoprinetti** [comment]
HI Florian works beautifully thank you

>> docker run --name cx-nexus --restart unless-stopped --network=cx-network
-d -e NEXUS_SECURITY_RANDOMPASSWORD=false sonatype/nexus3:3.21.1
3e0dcd0722a32d2dc8b822169b132838c5cb6dd2b87bfc93e86644fed39c663b
Waiting for the nexus server to
start......................................................................................................................................
success.
Initializing Nexus

Thanks and Regards
Matteo Prinetti


Am Mi., 1. Juli 2020 um 15:46 Uhr schrieb Florian Wilhelm <
notifications@github.com>:
