### ISSUE TITLE
Role-based Authorization Strategy Plugin Update

### ISSUE THREAD

**Issue by T1mey** [SAP/devops-docker-cx-server#88]
Please update Role-based Authorization Strategy to version 3.0

**Comment by T1mey** [comment]
@fwilhe 
Any update?

**Comment by fwilhe** [comment]
Hi @T1mey 

sorry, I've missed that issue (vacation time, and seems like it got lost afterwards).

We don't fix any specific versions, if you update your cx-server to the latest release v31 ist should have that plugin version, I've just checked in my local instance:

![image](https://user-images.githubusercontent.com/2292245/93321720-ccf61300-f812-11ea-802e-71b3918605f1.png)

Please note that the plugin-update feature can be broken if plugins were updated manually in Jenkins. See the [docs](https://github.com/SAP/devops-docker-cx-server/blob/master/docs/operations/cx-server-operations-guide.md#plugins) for plugin management in cx-server.

Hope that helps.

**Comment by T1mey** [comment]
thanks for the update. As we're on v31 and the pluginis still on 2.1 I guess we might have installed it before it was shipped with cx-server.
Any way to come back to the auto-update mechanism?

**Comment by fwilhe** [comment]
I'm not sure about your exact setup. Inside your `jenkins_home_volume` docker volume, which is mounted to `/var/jenkins_home` at runtime of the Jenkins master, there is a `plugins` directory. If that is empty, and Jenkins is restarting, it should be populated with the plugin versions from the image (i.e. what was latest when we built the release). You might first try to simply uninstall that one plugin, and testart cx-server using

```
./cx-server stop
./cx-server remove
./cx-server start
```

The "hard" way would be to configure another docker volume as `jenkins_home_volume`, but I think (not tested) you can get away with deleting the plugins dir. Note that any manual change in plugin versions (like update in the jenkins ui) will remove that single plugin from the update-cycle.
